apiVersion: v1
kind: LimitRange
metadata:
  name: guestbook-limits
  namespace: secure-app
spec:
  limits:
    # Container limits
    - max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: "100m"
        memory: 128Mi
      default:
        cpu: "200m"
        memory: 256Mi
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      type: Container
    # Pod limits
    - max:
        cpu: "2"
        memory: 2Gi
      type: Pod
    # PVC limits
    - max:
        storage: 10Gi
      min:
        storage: 1Gi
      type: PersistentVolumeClaim