apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guestbook-rolebinding
  namespace: secure-app
subjects:
  - kind: ServiceAccount
    name: guestbook-sa
    namespace: secure-app
roleRef:
  kind: Role
  name: guestbook-role
  apiGroup: rbac.authorization.k8s.io