apiVersion: v1
kind: Service
metadata:
  name: secure-guestbook
  namespace: secure-app
spec:
  selector:
    app: secure-guestbook
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP