apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: guestbook-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guestbook
  updatePolicy:
    updateMode: "Off"  # Recommendation mode only